import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { loadFilteredPiSkills } from "../src/pi-resources.js";
import { SkillExecutionGateway } from "../src/research/execution-gateway.js";
import { verifyExactRerun, type ComputationRecord } from "../src/research/execution-types.js";
import { createAgentSession, defineTool, SessionManager } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

const digest = (value: Buffer | string) => crypto.createHash("sha256").update(value).digest("hex");

test("filtered skillsOverride exposes only approved real SKILL.md packages", () => {
  const loaded = loadFilteredPiSkills(["exploratory-data-analysis", "stage1-finding-stability"]);
  assert.deepEqual(loaded.skills.map((item) => item.name), ["exploratory-data-analysis", "stage1-finding-stability"]);
  assert.equal(loaded.skills.some((item) => item.name === "bioservices"), false);
  assert.throws(() => loadFilteredPiSkills(["not-approved"]), /unavailable/);
});

test("Pi noTools builtin mode suppresses coding tools but retains policy custom tools", async () => {
  const parameters = Type.Object({});
  const tool = defineTool<typeof parameters, {}>({ name: "read_skill", label: "Read skill", description: "test", parameters, execute: async () => ({ content: [{ type: "text" as const, text: "ok" }], details: {} }) });
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), "sf-pi-tools-"));
  const created = await createAgentSession({ cwd, sessionManager: SessionManager.create(cwd, path.join(cwd, "sessions")), noTools: "builtin", customTools: [tool] });
  assert.deepEqual(created.session.getActiveToolNames(), ["read_skill"]);
  created.session.dispose();
});

test("gateway runs the unchanged upstream EDA script with frozen read-only inputs and a hashed receipt", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "sf-gateway-")); const run = path.join(root, "run"); const workspace = path.join(root, "workspace");
  fs.mkdirSync(path.join(run, "stage1"), { recursive: true }); const content = "gene,log2fc,adj_pvalue\nAPOE,1.2,0.01\n"; fs.writeFileSync(path.join(run, "stage1", "results.csv"), content);
  const scope: any = { artifacts: [{ path: "stage1/results.csv", sha256: digest(content) }] };
  const receipt = await new SkillExecutionGateway().run({ jobId: "job", stepId: "step", piSessionId: "pi", reasoningProfiles: ["data-scientist"], approvedSkills: ["exploratory-data-analysis"], skillId: "exploratory-data-analysis", script: "scripts/eda_analyzer.py", args: ["inputs/stage1/results.csv", "outputs/eda.md"], workspace, runPath: run, scope });
  assert.equal(receipt.exitCode, 0, receipt.stderr); assert.equal(receipt.activatedSkill, "exploratory-data-analysis");
  assert.equal(receipt.upstreamCommit, "209390194c85b3466259853417eeac81ea4f0976"); assert.equal(receipt.outputs[0].path, "outputs/eda.md");
  assert.equal(fs.statSync(path.join(workspace, "inputs", "stage1", "results.csv")).mode & 0o222, 0);
  assert.match(fs.readFileSync(path.join(workspace, "outputs", "eda.md"), "utf8"), /generated by the exploratory-data-analysis skill/);
});

test("gateway re-stages frozen read-only inputs across repeated skill runs in one workspace (no EACCES)", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "sf-gateway-restage-")); const run = path.join(root, "run"); const workspace = path.join(root, "workspace");
  fs.mkdirSync(path.join(run, "stage1"), { recursive: true }); const content = "gene,log2fc,adj_pvalue\nAPOE,1.2,0.01\n"; fs.writeFileSync(path.join(run, "stage1", "results.csv"), content);
  const scope: any = { artifacts: [{ path: "stage1/results.csv", sha256: digest(content) }] };
  const request = { jobId: "job", stepId: "step", piSessionId: "pi", reasoningProfiles: ["data-scientist"], approvedSkills: ["exploratory-data-analysis"], skillId: "exploratory-data-analysis", script: "scripts/eda_analyzer.py", args: ["inputs/stage1/results.csv", "outputs/eda.md"], workspace, runPath: run, scope };
  const gateway = new SkillExecutionGateway();
  const first = await gateway.run(request);
  assert.equal(first.exitCode, 0, first.stderr);
  const staged = path.join(workspace, "inputs", "stage1", "results.csv");
  assert.equal(fs.statSync(staged).mode & 0o222, 0, "first run froze the staged input read-only (0444)");
  // A second skill run in the same job workspace re-enters input staging; before
  // the fix, copyFileSync onto the read-only frozen copy threw EACCES here.
  const second = await gateway.run(request);
  assert.equal(second.exitCode, 0, second.stderr);
  assert.equal(fs.statSync(staged).mode & 0o222, 0, "staged input remains read-only after the second run");
  assert.equal(digest(fs.readFileSync(staged)), digest(content), "re-staged input content is intact");
});

test("gateway structurally rejects unapproved skills, path traversal, and networked scripts", async () => {
  const base: any = { jobId: "j", stepId: "s", piSessionId: "p", reasoningProfiles: [], approvedSkills: ["exploratory-data-analysis"], workspace: fs.mkdtempSync(path.join(os.tmpdir(), "sf-gateway-deny-")), runPath: "/tmp", scope: { artifacts: [] }, args: [] };
  const gateway = new SkillExecutionGateway();
  await assert.rejects(gateway.run({ ...base, skillId: "matplotlib", script: "scripts/plot_template.py" }), /not approved/);
  await assert.rejects(gateway.run({ ...base, skillId: "exploratory-data-analysis", script: "../SKILL.md" }), /not allowed/);
  await assert.rejects(gateway.run({ ...base, approvedSkills: ["citation-management"], skillId: "citation-management", script: "scripts/search_pubmed.py" }), /brokered egress/);
});

test("exact-rerun verification requires matching deterministic receipts, environment, inputs, and outputs", () => {
  const receipt: any = { determinism: "deterministic", environment: { lockHash: "env" }, inputs: [{ sha256: "in" }], outputs: [{ sha256: "out" }] };
  const record = { skillId: "exploratory-data-analysis", entrypoint: "summarize", executionReceipts: [receipt] } as ComputationRecord;
  assert.equal(verifyExactRerun(record, structuredClone(record)), true);
  const changed = structuredClone(record); (changed.executionReceipts as any[])[0].outputs[0].sha256 = "different";
  assert.equal(verifyExactRerun(record, changed), false);
  const stochastic = structuredClone(record); (stochastic.executionReceipts as any[])[0].determinism = "stochastic";
  assert.equal(verifyExactRerun(stochastic, structuredClone(stochastic)), false);
});
