# SignalFold network-skill image — runs ONE reviewed approved-external skill
# script per job, on a per-job --internal Docker bridge whose only egress-capable
# member is the egress-proxy sidecar. This is the (a)+(c) network mode: arbitrary
# run_python and the offline skills stay in the sealed --network none jail; only a
# REVIEWED network-skill script runs here, and even here every byte leaves through
# the TLS-intercepting proxy.
#
# The image trusts ONLY the egress CA (REQUESTS_CA_BUNDLE / SSL_CERT_FILE), so the
# proxy is the sole TLS peer it can reach for an allowlisted host. The vendored
# skills are baked read-only with the phone-home *_ai.py removed, exactly as the
# offline jail. GPL packages (bioservices) are isolated to THIS image and joined
# only when that skill is brought live — never imported into the Node/host process.
#
# Build:  ai-sidecar/run.sh net-build   (generates the egress CA first if missing)
ARG BASE_IMAGE=python:3.12-slim
FROM ${BASE_IMAGE}

# Deps for the first live network skill (pathway-enrichment): gseapy → Enrichr
# (maayanlab.cloud), gprofiler-official → g:Profiler (biit.cs.ut.ee). These pull
# pandas/numpy/scipy/matplotlib. Other network skills' deps are added here as each
# is brought live (e.g. bioservices, GPL-3.0, isolated to this image).
RUN pip install --no-cache-dir \
      gseapy==1.1.3 \
      gprofiler-official==1.0.0

# Vendored skills, baked read-only; phone-home scripts stripped (as the jail does).
COPY skills/scientific /opt/skills/scientific
RUN find /opt/skills/scientific -name '*_ai.py' -delete \
 && find /opt/skills/scientific -name '.DS_Store' -delete

# Trust ONLY the per-deployment egress CA — the proxy is the sole reachable TLS
# peer. (Generated by docker/egress-proxy/gen-certs.sh into docker/.egress-certs.)
COPY docker/.egress-certs/ca.crt /opt/egress-ca/ca.crt
ENV REQUESTS_CA_BUNDLE=/opt/egress-ca/ca.crt \
    SSL_CERT_FILE=/opt/egress-ca/ca.crt \
    PYTHONDONTWRITEBYTECODE=1

RUN mkdir -p /work/inputs /work/outputs
WORKDIR /work
# Driven one script at a time via `docker exec`; no long-running app process.
CMD ["sleep", "infinity"]
